apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql-spring
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mysql-spring
    tier: mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-1
  labels:
    type: local
spec:
  storageClassName: mysql
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/docker-entrypoint-initdb.d"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-10-0-0-252.us-west-2.compute.internal
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-0
  labels:
    type: local
spec:
  storageClassName: mysql
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/docker-entrypoint-initdb.d"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-10-0-0-231.us-west-2.compute.internal
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysql
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  iopsPerGB: "100"
  fsType: ext4
  encrypted: "false"
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - us-west-2b
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql-spring
spec:
  selector:
    matchLabels:
      app: mysql-spring
      tier: mysql
  serviceName: mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql-spring
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mawfia/mysql:{{ .Values.version | default 1.0 }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "swe645a3"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
      annotations:
        volume.beta.kubernetes.io/storage-class: mysql
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
